linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

output:
  format: colored-line-number

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  deadline: 5m 